{% set name = "intake-parquet" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake-parquet-{{ version }}.tar.gz
  sha256: 57e43795f53d5e44d375683f13532bae248005ff428d177613bc7607ce4a0f89

build:
  number: 0
  skip: true # [py<37 or py>311 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - intake
    - pandas
    - fastparquet
    - pyarrow
    - versioneer

test:
  imports:
    - intake_parquet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ContinuumIO/intake-parquet
  summary: Intake parquet plugin
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://github.com/ContinuumIO/intake-parquet
  doc_url: https://github.com/ContinuumIO/intake-parquet
  description: Intake parquet plugin
extra:
  recipe-maintainers:
    - martindurant
