{% set name = "intake-parquet" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake-parquet-{{ version }}.tar.gz
  sha256: 57e43795f53d5e44d375683f13532bae248005ff428d177613bc7607ce4a0f89

build:
  number: 0
  skip: true # [py<37 or s390x]
  script: 
    # Remove the out of date versioneer.py file from the source for py3.12 issue
    - rm -f versioneer.py  # [py>311]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    # necessary for setup.py resolution on py3.12 (likely due to missing versioneer.py)
    - versioneer ==0.29 # [py>311]
  run:
    - python
    - intake
    - pandas
    - fastparquet
    - pyarrow

test:
  source_files:
    - tests
  imports:
    - intake_parquet
  commands:
    - pip check
    # due to older pyarrow we need to avoid py3.12
    # test_discovery is broken and out of date
    - py.test --verbose -k "not test_discovery" tests # [py<311]
  requires:
    - pip
    - pytest
    # older pyarrow needed for out of date tests
    - pyarrow <=13.0.0

about:
  home: https://github.com/ContinuumIO/intake-parquet
  summary: Intake parquet plugin
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://github.com/ContinuumIO/intake-parquet
  doc_url: https://github.com/ContinuumIO/intake-parquet
  description: Intake parquet plugin

extra:
  recipe-maintainers:
    - martindurant